logs.config.file=classpath:/config/logs.properties
windowOptions.windowMultisample=1
windowOptions.fps=100
windowOptions.vsync=false
windowOptions.logging=@window.logging@
windowOptions.debug=@window.debug@
windowOptions.title=Satisplantory @project.version@
steam.appId=@steam.appId@
plugin.support=@plugin.support@
windowOptions.windowSize=800:600