logs.config.file=classpath:/config/logs.properties
windowOptions.windowMultisample=1
windowOptions.fps=100
windowOptions.vsync=false
windowOptions.logging=false
windowOptions.debug=true
windowOptions.title=Satisplantory @project.version@
steam.appId=@steam.appId@
