#maven plugin help mojo generation informations
#Sun Feb 01 18:31:40 CET 2026
destinationDirectory=/ssd2/workspaces/java2/plant-game/plant-game-autogen/target/generated-sources/plugin
helpPackageName=lu.kbra.plant_game.maven
