/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codedisaster_steamworks_SteamJNI */
#include "SteamJNI.h"
#include "steam_api.h"

#ifndef _Included_com_codedisaster_steamworks_SteamJNI
#define _Included_com_codedisaster_steamworks_SteamJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_codedisaster_steamworks_SteamJNI
 * Method:    getInstallDir
 * Signature: (I)Ljava/lang/String;
 */
 JNIEXPORT jstring JNICALL Java_SteamJNI_getInstallDir
   (JNIEnv *env, jclass clazz, jint appId) {

     char buffer[1024];
     buffer[0] = '\0';

     SteamApps()->GetAppInstallDir(appId, buffer, sizeof(buffer));

     return env->NewStringUTF(buffer);
 }

#ifdef __cplusplus
}
#endif
#endif
