name: Release (Release)

on:
  push:
    tags:
      - "v*"
      - "!v*-SNAPSHOT"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linux:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [{
              "id": "nexus.kbra.lu-releases",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_PASSWORD }}"
            }]
      - run: bash ./scripts/build-release-linux.sh

  windows:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [{
              "id": "nexus.kbra.lu-releases",
              "username": "${{ secrets.MAVEN_USERNAME }}",
              "password": "${{ secrets.MAVEN_PASSWORD }}"
            }]
      - run: bash ./scripts/build-release-windows.sh

  deploy:
    needs: [linux, windows]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [{
              "id": "steam",
              "username": "${{ secrets.STEAM_USERNAME }}",
              "password": "${{ secrets.STEAM_PASSWORD }}"
            }]
      - run: bash ./scripts/build-release-deploy.sh
